title: GPU and batched data augmentation with Kornia and PyTorch-Lightning
author: PL/Kornia team
created: 2021-06-11
updated: 2021-06-16
license: CC BY-SA
build: 4
tags:
  - Image
description: |
  In this tutorial we will show how to combine both Kornia and PyTorch Lightning
  to perform efficient data augmentation to train a simple model using the GPU in batch
  mode without additional effort.
requirements:
  - kornia
  - pytorch-lightning !=1.8.0, !=1.8.0.post1  # skip for PermissionError: [Errno 13] Permission denied: 'command'
  - torchmetrics
  - torchvision
  - matplotlib
  - pandas
  - seaborn
accelerator:
  - CPU
  - GPU
