title: GPU and batched data augmentation with Kornia and PyTorch-Lightning
author: PL/Kornia team
created: 2021-06-11
updated: 2021-06-16
license: CC BY-SA
build: 0
description: |
  In this tutorial we will show how to combine both Kornia.org and PyTorch Lightning
  to perform efficient data augmentation to train a simpple model using the GPU in batch
  mode without additional effort.
requirements:
  - pytorch-lightning
  - kornia
  - torchmetrics
  - torchvision
  - matplotlib
  - pandas
accelerator:
  - CPU
  - GPU
