title: How to write a PyTorch Lightning tutorial
author: PL team
created: 2021-06-15
updated: 2021-06-17
license: CC
description: |
  This is a template to show how to contribute a tutorial.
requirements:
  - pytorch-lightning
  - matplotlib
accelerator:
  - CPU
  - GPU
