title: Solving Titanic dataset with Lightning Flash
author: PL team
created: 2021-10-15
updated: 2022-04-10
license: CC
build: 0
description: |
  This is a template to show how to contribute a tutorial.
requirements:
  - lightning-flash[tabular]>=0.6
  - pandas>=1.0
  - matplotlib>=3.0
  - seaborn
accelerator:
  - CPU
  - GPU
datasets:
  kaggle:
    - titanic
