title: Introduction to Pytorch Lightning
author: PL team
created: 2020-12-21
updated: 2021-06-16
license: CC BY-SA
description: In this notebook, we'll go over the basics of lightning by preparing
  models to train on the [MNIST Handwritten Digits dataset](https://en.wikipedia.org/wiki/MNIST_database).
requirements:
- torchvision
accelerator:
- CPU
- GPU
