trigger:
  batch: true
  branches:
    include: [ main ]
pr: none
#stages:
#- stage: testing

jobs:

  - job: papermill
    # how much time to give 'run always even if cancelled tasks' before stopping them
    cancelTimeoutInMinutes: 2
    # how long to run the job before automatically cancelling
    # When 0 is specified, the maximum limit is used:
    # - For 360 minutes (6 hours) on Microsoft-hosted agents with a public project and public repository
    # - For 60 minutes on Microsoft-hosted agents with a private project or private repository
    timeoutInMinutes: 0

    pool: azure-gpus-persist
    # this need to have installed docker in the base image...
    container:
      # base ML image: mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04
      image: "pytorchlightning/pytorch_lightning:base-cuda-py3.9-torch1.10"
      # image: "pytorch/pytorch:1.7.1-cuda11.0-cudnn8-runtime"
      options: "-it --rm --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all --shm-size=32g"

    variables:
      ACCELERATOR: CPU,GPU
      PUB_BRANCH: publication
      PATH_DATASETS: "$(Build.Repository.LocalPath)/.datasets"
      COMMIT_MSG: $(echo "$(Build.SourceVersionMessage)" | head -n 1)
      COMMIT_HASH: "$(Build.SourceVersion)"

    steps:
    - bash: |
        lspci | egrep 'VGA|3D'
        whereis nvidia
        nvidia-smi
        python --version
      displayName: 'Image info & NVIDIA'

    - bash: |
        git fetch --all
        echo $(PUB_BRANCH)
        git ls-remote --heads origin ${PUB_BRANCH} | grep ${PUB_BRANCH} >/dev/null
        if [ "$?" == "1" ] ; then echo "Branch doesn't exist"; exit; fi
      displayName: 'Sanity branch check'

    - bash: |
        git config --global user.email "pipelines@azure.com"
        git config --global user.name "Azure Pipelines"
        printf "commit hash:\n $(COMMIT_HASH)\n"
        printf "commit message:\n $(COMMIT_MSG)\n"
      displayName: 'Set Git user'

    - bash: |
        pip --version
        pip install --requirement requirements.txt
        pip install --requirement requirements/data.txt
        pip list
      displayName: 'Install dependencies'

    - bash: |
        set -e
        python -c "import torch ; mgpu = torch.cuda.device_count() ; assert mgpu > 0, f'GPU: {mgpu}'"
        python -m papermill --version
      displayName: 'Sanity check'

    - bash: |
        current_branch=$(cut -d '/' -f3- <<< $(Build.SourceBranch))
        printf "$current_branch\n"
        bash .actions/git-diff-sync.sh $current_branch $(PUB_BRANCH)
      displayName: 'Compare changes & sync'

    - script: |
        COUNT=$(python -c "lines = open('changed-folders.txt').readlines() ; print(len(lines))")
        printf "Changed folders: $COUNT\n"
        echo "##vso[task.setvariable variable=folders;isOutput=true]$COUNT"
      name: changed

    - script: |
        COUNT=$(python -c "lines = open('dropped-folders.txt').readlines() ; print(len(lines))")
        printf "Dropped folders: $COUNT\n"
        echo "##vso[task.setvariable variable=folders;isOutput=true]$COUNT"
      name: dropped

    - bash: |
        while IFS= read -r line; do
            python .actions/assistant.py convert-ipynb $line
        done <<< $(cat changed-folders.txt)
      condition: gt(variables['changed.folders'], 0)
      displayName: 'Generate notebook'

    - bash: |
        mkdir $(PATH_DATASETS)
        # render the actual notebooks
        while IFS= read -r line; do
            python .actions/assistant.py bash-render $line > .actions/_ipynb-render.sh
            cat .actions/_ipynb-render.sh
            bash .actions/_ipynb-render.sh
        done <<< $(cat changed-folders.txt)
        git status
        git commit -m "publish [GPU]: $(COMMIT_HASH)"
      condition: and(succeeded(), gt(variables['changed.folders'], 0))
      env:
        KAGGLE_USERNAME: $(KAGGLE_USERNAME)
        KAGGLE_KEY: $(KAGGLE_KEY)
      displayName: 'Render notebook'

    - bash: |
        # remove notebooks which have moved
        while IFS= read -r line; do
            git rm .notebooks/$line.ipynb
            git rm .notebooks/$line.yaml
        done <<< $(cat dropped-folders.txt)
        git status
        git commit -m "prune: $(COMMIT_HASH)"
      condition: gt(variables['dropped.folders'], 0)
      displayName: 'Prune notebook'

    - bash: |
        git status
        git push https://$(PAT_GHOST)@github.com/PyTorchLightning/lightning-tutorials.git $(PUB_BRANCH)
      displayName: 'Finish push'
