title: Basics of Graph Neural Networks
author: Phillip Lippe
created: 2021-06-07
updated: 2021-06-07
license: CC
description: |
  This tutorial is a primer on Graph Neural Networks.
  We discuss basic layers such as Graph Convolutions and Graph Attention Layer.
  Further, we apply GNNs to semi-supervised node classification and molecule categorization.
  This notebook is part of a lecture series on Deep Learning at the University of Amsterdam.
  The full list of tutorials can be found at https://uvadlc-notebooks.rtfd.io.
requirements:
  - torch-scatter
  - torch-sparse
  - torch-cluster
  - torch-spline-conv
  - torch-geometric
  - pytorch-lightning
pip__find-link:
  # - https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html
  - https://pytorch-geometric.com/whl/torch-%(TORCH_VERSION)s+cu%(CUDA_VERSION)s.html
accelerator:
  - CPU
  - GPU
