title: Tabular Classification on Titanic Dataset
author: Ethan Harris (ethan@pytorchlightning.ai)
created: 2021-11-23
updated: 2022-08-26
license: CC BY-SA
build: 3
tags:
  - Tabular Classification
  - Tabular
description: |
  In this notebook, we'll go over the basics of lightning Flash by training a TabularClassifier on [Titanic Dataset](https://www.kaggle.com/c/titanic).
requirements:
  - pytorch-lightning==0.6.0
  - lightning-flash[tabular]>=0.6.0
accelerator:
  - GPU
  - CPU
