title: PyTorch Lightning Basic GAN Tutorial
author: PL team
created: 2020-12-21
updated: 2021-06-16
license: CC BY-SA
build: 0
description: |
  How to train a GAN!

  Main takeaways:
  1. Generator and discriminator are arbitrary PyTorch modules.
  2. training_step does both the generator and discriminator training.
requirements:
  - torchvision
accelerator:
  - CPU
  - GPU
