pr:
  - main
  - release/*

jobs:
  - job: treon
    # how long to run the job before automatically cancelling
    timeoutInMinutes: 45
    # how much time to give 'run always even if cancelled tasks' before stopping them
    cancelTimeoutInMinutes: 2

    pool: gridai-spot-pool

    # this need to have installed docker in the base image...
    container:
      # base ML image: mcr.microsoft.com/azureml/openmpi3.1.2-cuda10.2-cudnn8-ubuntu18.04
      image: "pytorchlightning/pytorch_lightning:base-cuda-py3.8-torch1.7"
      #endpoint: azureContainerRegistryConnection
      options: "--runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all"

    workspace:
      clean: all
    variables:
      ACCELERATOR: GPU

    steps:

    - bash: |
        lspci | egrep 'VGA|3D'
        whereis nvidia
        nvidia-smi
        python --version
        pip --version
        pip list
      displayName: 'Image info & NVIDIA'

    - bash: |
        pip --version
        pip install --requirement requirements.txt
        pip list
      displayName: 'Install dependencies'

    - bash: |
        python -c "import torch ; mgpu = torch.cuda.device_count() ; assert mgpu > 0, f'GPU: {mgpu}'"
      displayName: 'Env details'
    - bash: |
        head=$(git rev-parse origin/main)
        git diff --name-only $head --output=master-diff.txt
        python .actions/helpers.py group-folders master-diff.txt
        echo "Changed folder:"
        cat changed-folders.txt
        echo "Dropped folder:"
        cat dropped-folders.txt
      displayName: 'Process folders'

    - bash: |
        NB_DIRS=$( python -c "lines = open('changed-folders.txt').readlines(); print(len(lines))" )
        echo "Number of chnaged folders: $NB_DIRS"
        echo "##vso[task.setvariable variable=chnaged_dirs]$NB_DIRS"
      displayName: 'Count changed'

    - bash: |
        while IFS= read -r line; do
            bash .actions/ipynb-generate.sh $line
        done <<< $(cat changed-folders.txt)
      condition: gt( chnaged_dirs, 0 )
      displayName: 'Generate notebook'

    - bash: |
        while IFS= read -r line; do
            bash .actions/ipynb-test.sh $line
        done <<< $(cat changed-folders.txt)
      displayName: 'Treon notebook'
