title: TPU training with PyTorch Lightning
author: Lightning.ai
created: 2020-12-21
license: CC BY-SA
tags:
  - Image
description: In this notebook, we'll train a model on TPUs. Updating one Trainer flag is all you need for that.
  The most up to documentation related to TPU training can be found
  [here](https://lightning.ai/docs/pytorch/stable/accelerators/tpu.html).
accelerator:
  - TPU
