name: validate Docs

on:  # Trigger the workflow on push or pull request
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-20.04
    env:
      PUB_BRANCH: publication
      PATH_DATASETS: ${{ github.workspace }}/.datasets
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch all history for all branches and tags
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('docs/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          # install Texlive, see https://linuxconfig.org/how-to-install-latex-on-ubuntu-20-04-focal-fossa-linux
          sudo apt-get update
          sudo apt-get install -y cmake pandoc
          sudo apt-get install -y texlive-latex-extra dvipng texlive-pictures
          pip --version
          pip install --quiet --requirement requirements.txt
          pip install --quiet --requirement docs/requirements.txt
          pip list
        shell: bash

      - name: Process folders
        run: |
          mkdir -p ${PATH_DATASETS}
          head=$(git rev-parse origin/"${{ github.base_ref }}")
          git diff --name-only $head --output=master-diff.txt
          python .actions/assistant.py group-folders master-diff.txt
          printf "Changed folders:\n"
          cat changed-folders.txt
        shell: bash

      - name: ">> output"
        id: changed
        run: python -c "lines = open('changed-folders.txt').readlines(); print(f'::set-output name=dirs::{len(lines)}')"
      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
          global: true

      - name: Sync to pub
        run: git merge -s resolve origin/$PUB_BRANCH

      - name: Generate notebook
        if: steps.changed.outputs.dirs != 0
        run: |
          while IFS= read -r line; do
              python .actions/assistant.py augment-script $line
              python .actions/assistant.py bash-render $line > .actions/_ipynb-render.sh
              cat .actions/_ipynb-render.sh
              bash .actions/_ipynb-render.sh
          done <<< $(cat changed-folders.txt)
        env:
          DRY_RUN: 1
        shell: bash

      - name: Make Documentation
        working-directory: ./docs
        run: |
          # First run the same pipeline as Read-The-Docs
          make html --debug SPHINXOPTS="-W --keep-going" -b linkcheck

      - name: Upload built docs
        uses: actions/upload-artifact@v2
        with:
          name: docs-results-${{ github.sha }}
          path: docs/build/html/
        # Use always() to always run this step to publish test results when there are test failures
        if: success()
