name: Check Schema

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    uses: Lightning-AI/utilities/.github/workflows/check-schema.yml@main
    with:
      # skip azure due to the wrong schema file by MSFT
      # https://github.com/Lightning-AI/lightning-flash/pull/1455#issuecomment-1244793607
      azure-dir: ".azure"
