name: CI testing

# see: https://help.github.com/en/actions/reference/events-that-trigger-workflows
on:  # Trigger the workflow on push or pull request
  pull_request: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  nbval:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python-version: [3.8]
    # Timeout: https://stackoverflow.com/a/59076067/4521646
    timeout-minutes: 55
    env:
      PATH_DATASETS: ${{ github.workspace }}/.datasets

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # fetch all history for all branches and tags
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          sudo apt-get update --fix-missing
          sudo apt install -y ffmpeg
          pip --version
          pip install --requirement requirements.txt --find-links https://download.pytorch.org/whl/cpu/torch_stable.html
          pip install --requirement requirements/data.txt
          pip list
        shell: bash

      - name: Process folders
        run: |
          mkdir ${PATH_DATASETS}
          head=$(git rev-parse origin/${{ github.base_ref }})
          git diff --name-only $head --output=target-diff.txt
          python .actions/assistant.py group-folders target-diff.txt
          printf "Changed folders:\n"
          cat changed-folders.txt
        shell: bash

      - name: ">> output"
        id: changed
        run: python -c "lines = open('changed-folders.txt').readlines(); print(f'::set-output name=dirs::{len(lines)}')"

      - name: Generate notebook
        if: steps.changed.outputs.dirs != 0
        run: |
          while IFS= read -r line; do
              python .actions/assistant.py convert-ipynb $line
          done <<< $(cat changed-folders.txt)
        shell: bash

      - name: PyTest notebook
        if: success() && steps.changed.outputs.dirs != 0
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          set -e
          sudo apt install -y tree
          while IFS= read -r line; do
              python .actions/assistant.py bash-test $line
              cat .actions/_ipynb-test.sh
              bash .actions/_ipynb-test.sh
          done <<< $(cat changed-folders.txt)
        shell: bash
