name: Deploy Docs
on:
  push:
    branches: [publication]
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/docs-deploy.yml"
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Publish notebook"]
    types:
      - completed

jobs:
  # https://github.com/marketplace/actions/deploy-to-github-pages
  build-docs-deploy:
    runs-on: ubuntu-20.04
    env:
      PATH_DATASETS: ${{ github.workspace }}/.datasets
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          ref: publication
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
          cache: pip

      - name: List notebooks
        working-directory: .notebooks/
        run: |
          pip install -q py-tree
          py-tree .

      - name: Install dependencies
        run: |
          mkdir -p ${PATH_DATASETS}
          sudo apt-get update --fix-missing
          sudo apt-get install -y cmake pandoc
          # install Texlive, see https://linuxconfig.org/how-to-install-latex-on-ubuntu-20-04-focal-fossa-linux
          sudo apt-get install -y texlive-latex-extra dvipng texlive-pictures
          pip install -q -r _requirements/docs.txt
          pip list
        shell: bash

      - name: Make Documentation
        working-directory: ./_docs
        run: make html --jobs $(nproc)

      - name: Copied notebooks [debugging]
        if: failure()
        working-directory: ./_docs/source/
        run: py-tree notebooks

      - name: Deploy 🚀
        if: ${{ github.event_name != 'pull_request' }}
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: _docs/build/html # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
          target-folder: docs # If you'd like to push the contents of the deployment folder into a specific directory
          single-commit: true # you'd prefer to have a single commit on the deployment branch instead of full history
