name: Deploy Docs
on:
  push:
    branches: [publication]
  workflow_dispatch: {}
  workflow_run:
    workflows: ["Publish notebook"]
    types:
      - completed

jobs:
  # https://github.com/marketplace/actions/deploy-to-github-pages
  build-docs-deploy:
    runs-on: ubuntu-20.04
    env:
      PUB_BRANCH: publication
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          ref: $PUB_BRANCH
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}-${{ hashFiles('docs/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          # install Texlive, see https://linuxconfig.org/how-to-install-latex-on-ubuntu-20-04-focal-fossa-linux
          sudo apt-get update
          sudo apt-get install -y cmake pandoc
          sudo apt-get install -y texlive-latex-extra dvipng texlive-pictures
          pip --version
          pip install --quiet --requirement docs/requirements.txt
          pip list
        shell: bash

      - name: Make Documentation
        working-directory: ./docs
        run: make html --jobs $(nproc)

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: $PUB_BRANCH
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs/build/html # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          TARGET_FOLDER: docs # If you'd like to push the contents of the deployment folder into a specific directory
        if: success()
